export const DataMenu = [
   {
      "Id": 0,
      "Content": "trang chủ",
      "SubMenu": null,
      "Display": 1,
      "HiddenMenu": false,
      "HiddenHomePage": true,
      "DisplayShowOnCateBoxHome": 1,
   },
   {
      "Id": 1,
      "Content": "giới thiệu",
      "SubMenu": null,
      "Display": 2,
      "HiddenMenu": false,
      "HiddenHomePage": true,
      "DisplayShowOnCateBoxHome": 1,
   },
   {
      "Id": 2,
      "Content": "Thông tin thời sự",
      "SubMenu": null,
      "Display": 2,
      "HiddenMenu": false,
      "HiddenHomePage": false,
      "DisplayShowOnCateBoxHome": 1,
   },
   {
      "Id": 3,
      "Content": "Hoạt động đảng ủy",
      "SubMenu": null,
      "Display": 2,
      "HiddenMenu": false,
      "HiddenHomePage": true,
      "DisplayShowOnCateBoxHome": 1,
   },
   {
      "Id": 4,
      "Content": "Xây dựng đảng",
      "SubMenu": [
         {
            "Id": 5,
            "Content": "Hoạt động Đảng bộ liên hiệp",
            "SubMenu": null,
            "Display": 2,
            "HiddenMenu": false,
            "HiddenHomePage": false,
            "DisplayShowOnCateBoxHome": 1,
         },
         {
            "Id": 6,
            "Content": "Hoạt động công đoàn và đoàn thanh niên liên hiệp",
            "SubMenu": null,
            "Display": 2,
            "HiddenMenu": false,
            "HiddenHomePage": true,
            "DisplayShowOnCateBoxHome": 1,
         }
      ],
      "Display": 2,
      "HiddenMenu": false,
      "HiddenHomePage": false,
      "DisplayShowOnCateBoxHome": 1,  
   },
   {
      "Id": 7,
      "Content": "Văn bản",
      "SubMenu": null,
      "Display": 3,
      "HiddenMenu": false,
      "HiddenHomePage": true,
      "DisplayShowOnCateBoxHome": 1,
   },
   {
      "Id": 8,
      "Content": "Nhân sự mới",
      "SubMenu": [
         {
            "Id": 9,
            "Content": "Nhân sự cấp ủy",
            "SubMenu": null,
            "Display": 2,
            "HiddenMenu": false,
            "HiddenHomePage": true,
            "DisplayShowOnCateBoxHome": 1,
         },
         {
            "Id": 10,
            "Content": "Nhân sự chính quyền",
            "SubMenu": null,
            "Display": 2,
            "HiddenMenu": false,
            "HiddenHomePage": true,
            "DisplayShowOnCateBoxHome": 1,
         }
      ],
      "Display": 2,
      "HiddenMenu": false,
      "HiddenHomePage": true,
      "DisplayShowOnCateBoxHome": 1,
   },
   {
      "Id": 11,
      "Content": "Trao đổi thảo luận",
      "SubMenu": null,
      "Display": 2,
      "HiddenMenu": false,
      "HiddenHomePage": true,
      "DisplayShowOnCateBoxHome": 1,
   },
   {
      "Id": 12,
      "Content": "Thư viện ảnh",
      "Display": 2,
      "HiddenMenu": true,
      "HiddenHomePage": false,
      "DisplayShowOnCateBoxHome": 2,
   }
]